### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by gevs007** [cosmii02/RacingDSX#2]
Hi! I have tried it to enable in many ways but it does not work at all. My Forza only works with Xbox emulation. I dont understand what am I doing wrong. There is no any video guidance I can use. I have checked 100 times ports numbers, all the settings to be matched the ones mentioned in the text guide. Nothing is working. Could you please help me with the issue I have? I think it comes from the fact that I am emulating Xbox controller. But  when I change to dualshock it stops working at all. Using Xbox emulation, I dont have even rumble vibrations. The only way to get it is connecting solely by steam app. Could you please tell me what am I doing wrong?

**Comment by cosmii02** [comment]
You should use xbox emulation, enable vibrations from dsx and then use the mod.

**Comment by Novationo** [comment]
I wasn't able to get ForzaDSX to work with the new version of DSX on Steam, only the old [_DualsenseX_ Github version](https://github.com/Paliverse/DualSenseX).
I also had trouble when I tried running it since I forgot to turn Forza's telemetry on, so I would double check that as well.

Edit: if you experience double inputs (i.e. a double click on the map, or skipping gears) with DualSenseX, I'm pretty sure its because of inproper HidHide Support. But you can [disable Steam's input inside of steams settings like this](https://i.imgur.com/7ZSXuLb.png), and that resolved the issue for me at least :)

Hope this helps!

**Comment by cosmii02** [comment]
Updated readme with short instructions for fh4 and fm7

**Comment by s0updev** [comment]
> I wasn't able to get ForzaDSX to work with the new version of DSX on Steam, only the old [_DualsenseX_ Github version](https://github.com/Paliverse/DualSenseX). I also had trouble when I tried running it since I forgot to turn Forza's telemetry on, so I would double check that as well.
> 
> Edit: if you experience double inputs (i.e. a double click on the map, or skipping gears) with DualSenseX, I'm pretty sure its because of inproper HidHide Support. But you can [disable Steam's input inside of steams settings like this](https://i.imgur.com/7ZSXuLb.png), and that resolved the issue for me at least :)
> 
> Hope this helps!

I'm playing through gamepass so I can't disable the steam input for fh5, but even killing steam doesn't help, dunno what to do

**Comment by s0updev** [comment]
I have double inputs

**Comment by s0updev** [comment]
nvm i used HidHide and fixed it
